import { StyleSheet } from 'react-native';
import {
  COLORS,
  SPACING,
  SIZES,
  TYPOGRAPHY,
} from '../constants';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
    paddingHorizontal: SPACING.CONTAINER_HORIZONTAL,
    paddingTop: SPACING.CONTAINER_TOP,
  },
  centered: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.BACKGROUND,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    gap: SPACING.HEADER_GAP,
    paddingLeft: SPACING.HEADER_PADDING_LEFT,
    paddingRight: SPACING.HEADER_PADDING_LEFT,
    paddingVertical: 12,
    position: 'relative',
    zIndex: 20000,
    overflow: 'visible',
  },
  logo: {
    width: SIZES.LOGO_WIDTH,
    height: SIZES.LOGO_HEIGHT,
    borderRadius: SIZES.LOGO_BORDER_RADIUS,
    backgroundColor: COLORS.SURFACE,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  headerText: {
    flex: 1,
  },
  title: {
    fontSize: TYPOGRAPHY.TITLE_SIZE,
    fontWeight: '700',
    color: COLORS.TEXT_PRIMARY,
  },
  subtitle: {
    color: COLORS.TEXT_SECONDARY,
    marginTop: 2,
  },
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: SPACING.SEARCH_ROW_MARGIN_BOTTOM,
    gap: SPACING.SEARCH_ROW_GAP,
    paddingLeft: SPACING.SEARCH_ROW_PADDING_HORIZONTAL,
    paddingRight: SPACING.SEARCH_ROW_PADDING_HORIZONTAL,
  },
  input: {
    flex: 1,
    backgroundColor: COLORS.SURFACE,
    borderRadius: SIZES.BORDER_RADIUS_MEDIUM,
    paddingHorizontal: SPACING.INPUT_PADDING_HORIZONTAL,
    paddingVertical: SPACING.INPUT_PADDING_VERTICAL,
    borderWidth: 1,
    borderColor: COLORS.BORDER_LIGHT,
    fontWeight: '600',
    color: COLORS.TEXT_PRIMARY,
  },
  clearButton: {
    paddingVertical: SPACING.INPUT_PADDING_VERTICAL,
    paddingHorizontal: SPACING.INPUT_PADDING_HORIZONTAL,
    backgroundColor: COLORS.BUTTON_SECONDARY_BG,
    borderRadius: SIZES.BORDER_RADIUS_MEDIUM,
  },
  clearText: {
    color: COLORS.BUTTON_SECONDARY_TEXT,
    fontWeight: '600',
  },
  highlight: {
    backgroundColor: COLORS.HIGHLIGHT_BG,
    borderRadius: SIZES.BORDER_RADIUS_MEDIUM,
    padding: SPACING.HIGHLIGHT_PADDING,
    marginBottom: SPACING.HIGHLIGHT_MARGIN_BOTTOM,
    borderWidth: 1,
    borderColor: COLORS.HIGHLIGHT_BORDER,
  },
  listContent: {
    paddingBottom: SPACING.LIST_CONTENT_PADDING_BOTTOM,
    paddingHorizontal: SPACING.LIST_CONTENT_PADDING_HORIZONTAL,
  },
  card: {
    backgroundColor: COLORS.SURFACE,
    borderRadius: SIZES.BORDER_RADIUS_LARGE,
    padding: SPACING.CARD_PADDING,
    marginBottom: SPACING.CARD_MARGIN_BOTTOM,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
  },
  part: {
    fontSize: TYPOGRAPHY.PART_SIZE,
    fontWeight: '700',
    color: COLORS.TEXT_PRIMARY,
  },
  label: {
    marginTop: 6,
    fontSize: TYPOGRAPHY.LABEL_SIZE,
    color: COLORS.TEXT_MUTED,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  value: {
    fontSize: TYPOGRAPHY.VALUE_SIZE,
    color: COLORS.TEXT_PRIMARY,
    marginTop: 2,
  },
  muted: {
    color: COLORS.TEXT_MUTED,
    textAlign: 'center',
    marginTop: 12,
  },
  error: {
    color: COLORS.ERROR,
    fontWeight: '700',
    paddingHorizontal: 24,
    textAlign: 'center',
  },
  cardHeader: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: SPACING.CARD_HEADER_GAP,
  },
  cardContent: {
    flex: 1,
  },
  datasheetButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: SPACING.BUTTON_PADDING_VERTICAL,
    paddingHorizontal: SPACING.BUTTON_PADDING_HORIZONTAL,
    backgroundColor: COLORS.PRIMARY,
    borderRadius: SIZES.BORDER_RADIUS_SMALL,
    minWidth: SIZES.BUTTON_MIN_WIDTH,
  },
  datasheetButtonLabel: {
    fontSize: TYPOGRAPHY.BUTTON_LABEL_SIZE,
    color: COLORS.SURFACE,
    fontWeight: '600',
  },
  modalContainer: {
    flex: 1,
    backgroundColor: COLORS.BACKGROUND,
  },
  modalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SPACING.MODAL_HEADER_PADDING_HORIZONTAL,
    paddingVertical: SPACING.MODAL_HEADER_PADDING_VERTICAL,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER,
    backgroundColor: COLORS.SURFACE,
  },
  modalTitle: {
    fontSize: TYPOGRAPHY.MODAL_TITLE_SIZE,
    fontWeight: '700',
    color: COLORS.TEXT_PRIMARY,
    flex: 1,
  },
  closeButton: {
    width: SIZES.CLOSE_BUTTON_SIZE,
    height: SIZES.CLOSE_BUTTON_SIZE,
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: SIZES.CLOSE_BUTTON_BORDER_RADIUS,
    backgroundColor: COLORS.BUTTON_SECONDARY_BG,
  },
  closeButtonText: {
    fontSize: TYPOGRAPHY.CLOSE_BUTTON_SIZE,
    color: COLORS.BUTTON_SECONDARY_TEXT,
    fontWeight: '600',
  },
  webview: {
    flex: 1,
    backgroundColor: COLORS.SURFACE,
  },
  webviewLoading: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: COLORS.SURFACE,
  },
  loadingText: {
    marginTop: 12,
    fontSize: TYPOGRAPHY.LOADING_TEXT_SIZE,
    color: COLORS.TEXT_MUTED,
  },
  webviewPlaceholder: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    padding: 32,
    backgroundColor: COLORS.BACKGROUND,
  },
  placeholderTitle: {
    fontSize: TYPOGRAPHY.PLACEHOLDER_TITLE_SIZE,
    fontWeight: '700',
    color: COLORS.TEXT_PRIMARY,
    marginBottom: 12,
  },
  placeholderText: {
    fontSize: TYPOGRAPHY.PLACEHOLDER_TEXT_SIZE,
    color: COLORS.TEXT_MUTED,
    textAlign: 'center',
    marginBottom: 24,
  },
  openButton: {
    backgroundColor: COLORS.PRIMARY,
    paddingVertical: SPACING.BUTTON_PADDING_VERTICAL,
    paddingHorizontal: 24,
    borderRadius: SIZES.BORDER_RADIUS_SMALL,
  },
  openButtonText: {
    color: COLORS.SURFACE,
    fontSize: TYPOGRAPHY.OPEN_BUTTON_TEXT_SIZE,
    fontWeight: '600',
  },
  navbar: {
    backgroundColor: COLORS.SURFACE,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 4,
    shadowOffset: { width: 0, height: 2 },
    elevation: 3,
    marginBottom: SPACING.HEADER_MARGIN_BOTTOM,
    position: 'relative',
    zIndex: 20000,
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  languageSelectContainer: {
    position: 'relative',
    zIndex: 10000,
  },
  languageButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 10,
    borderRadius: SIZES.BORDER_RADIUS_SMALL,
    cursor: 'pointer',
    transition: 'opacity 0.2s',
    gap: 4,
  },
  languageButtonPressed: {
    opacity: 0.7,
    backgroundColor: COLORS.BORDER_LIGHT,
  },
  languageButtonText: {
    fontSize: 20,
  },
  languageDropdownArrow: {
    fontSize: 10,
    color: COLORS.TEXT_MUTED,
  },
  languageDropdown: {
    position: 'absolute',
    top: '100%',
    right: 0,
    marginTop: 4,
    backgroundColor: COLORS.SURFACE,
    borderRadius: SIZES.BORDER_RADIUS_MEDIUM,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 8,
    minWidth: 140,
    zIndex: 10001,
  },
  languageDropdownOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    borderRadius: SIZES.BORDER_RADIUS_SMALL,
  },
  languageDropdownOptionSelected: {
    backgroundColor: COLORS.HIGHLIGHT_BG,
  },
  languageDropdownOptionPressed: {
    opacity: 0.7,
    backgroundColor: COLORS.BORDER_LIGHT,
  },
  languageDropdownOptionFlag: {
    fontSize: 20,
    marginRight: 10,
  },
  languageDropdownOptionText: {
    fontSize: TYPOGRAPHY.VALUE_SIZE,
    color: COLORS.TEXT_PRIMARY,
    fontWeight: '500',
  },
  languageDropdownOptionTextSelected: {
    color: COLORS.PRIMARY,
    fontWeight: '600',
  },
  navbarButton: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: SIZES.BORDER_RADIUS_SMALL,
    cursor: 'pointer',
    transition: 'opacity 0.2s',
  },
  navbarButtonPressed: {
    opacity: 0.7,
    backgroundColor: COLORS.BORDER_LIGHT,
  },
  navbarButtonText: {
    color: COLORS.TEXT_SECONDARY,
    fontSize: 14,
    fontWeight: '500',
  },
  aboutContent: {
    flex: 1,
    padding: SPACING.MODAL_HEADER_PADDING_HORIZONTAL,
    paddingTop: 24,
  },
  aboutSection: {
    marginBottom: 24,
  },
  aboutTitle: {
    fontSize: TYPOGRAPHY.MODAL_TITLE_SIZE,
    fontWeight: '700',
    color: COLORS.TEXT_PRIMARY,
    marginBottom: 16,
  },
  aboutText: {
    fontSize: TYPOGRAPHY.VALUE_SIZE,
    color: COLORS.TEXT_SECONDARY,
    lineHeight: 22,
    marginBottom: 8,
  },
  aboutDeveloperSection: {
    marginTop: 24,
    paddingTop: 24,
    borderTopWidth: 1,
    borderTopColor: COLORS.BORDER,
  },
  aboutDeveloperLabel: {
    fontSize: TYPOGRAPHY.LABEL_SIZE,
    color: COLORS.TEXT_MUTED,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    marginBottom: 8,
  },
  aboutDeveloperName: {
    fontSize: TYPOGRAPHY.PART_SIZE,
    fontWeight: '600',
    color: COLORS.PRIMARY,
  },
});
